---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  # playbook: default.yml
  # require_chef_for_busser: true
  require_ruby_for_busser: true

verifier:
  ruby_bindir: '/usr/bin'

platforms:
  - name: ubuntu-14.04
  # - name: centos-7.2

suites:
  - name: default